# This is a configuration file for evaluating the RTDETRv2 model.
# Note: All paths are relative to the directory where the script is run.

model_dir: "./checkpoints/rtdetr_v2_r50vd/test/best_model" # Directory of the model and image processor
img_dir: "../data/test/images" # Image directory. May be omitted if the annotation file contains full paths to the images.
cocoann_file: "../data/test/cocoann.json" # COCO annotation file

threshold: 0.01 # Confidence threshold for predictions